backend:
  name: git-gateway
  branch: master 
  site_domain: urora.netlify.app
publish_mode: editorial_workflow
media_folder: "assets/image"
public_folder: "/_site/image"
collections:
  - name: "post" 
    label: "Post" 
    folder: "_posts" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm", format: "L"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: 'page'
    label: 'Page'    
    preview: false
    files:
      - label: 'About'
        name: 'about'
        file: '_posts/1999-09-09-about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Body', name: 'body', widget: 'markdown' }