backend:
  name: git-gateway
  branch: master 
  site_domain: urora.netlify.app
  local_backend: true

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8081/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']
publish_mode: editorial_workflow
media_folder: "assets/image"
public_folder: "/_site/image"
collections:
  - name: "post" 
    label: "Post" 
    folder: "_posts" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "list", default: ["Kinten","(request more)"]}
      - {label: "Publish Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm", format: "L"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: 'page'
    label: 'Page'    
    preview: false
    files:
      - label: 'About'
        name: 'about'
        file: '_posts/1999-09-09-about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Body', name: 'body', widget: 'markdown' }